### PR TITLE
build Windows packages

### PR DESCRIPTION
**Pull request by KrisThielemans**
attempt to enable windows and Mac builds (addresses #9)

### CODE REVIEW

**Comment by KrisThielemans** [comment]
so... all checks passed, but none of them test Windows or OSX. I must be missing something!

**Comment by olivierverdier** [comment]
Mmh, weird indeed...

**Comment by KrisThielemans** [comment]
@conda-forge-admin, please rerender

**Comment by KrisThielemans** [comment]
For whatever reason, I don't even have the "allow edits from maintainers" tick box in the right, so I cannot enable it. Sigh.

**Comment by KrisThielemans** [comment]
@casperdcl @olivierverdier one of you feels like rerendering this for  me (https://conda-forge.readthedocs.io/en/latest/conda_smithy.html)? My own conda install seems broken at the moment... I guess you'd have to do a PR onto my PR.

**Comment by KrisThielemans** [comment]
ok, so now they're running.

Windows jobs are failing before it gets to our own `bld.bat` though, in fact [apparently when running `vsvarsall.bat`](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=131276&view=logs&j=171a126d-c574-5c8c-1269-ff3b989e923d&t=7225e372-3a5e-5b11-c153-719d50bbeacd&l=407)
```
2020-03-15T09:38:56.5432296Z %SRC_DIR%>CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\..\..\VC\vcvarsall.bat" amd64  
2020-03-15T09:39:00.5430773Z CMake Error at CMakeLists.txt:27 (PROJECT):
2020-03-15T09:39:00.5431717Z   Failed to run MSBuild command:
2020-03-15T09:39:00.5432006Z 
2020-03-15T09:39:00.5432269Z     MSBuild.exe
2020-03-15T09:39:00.5432581Z 
2020-03-15T09:39:00.5432882Z   to get the value of VCTargetsPath:
2020-03-15T09:39:00.5433153Z 
2020-03-15T09:39:00.5433660Z     Microsoft (R) Build Engine version 4.8.3761.0
2020-03-15T09:39:00.5434096Z     [Microsoft .NET Framework, version 4.0.30319.42000]
2020-03-15T09:39:00.5434576Z     Copyright (C) Microsoft Corporation. All rights reserved.
2020-03-15T09:39:00.5434992Z     
2020-03-15T09:39:00.5435308Z     Build started 3/15/2020 9:39:00 AM.
2020-03-15T09:39:00.5435850Z     Project "D:\bld\stir_1584264789343\work\build\CMakeFiles\3.16.4\VCTargetsPath.vcxproj" on node 1 (default targets).
2020-03-15T09:39:00.5436820Z     D:\bld\stir_1584264789343\work\build\CMakeFiles\3.16.4\VCTargetsPath.vcxproj(15,2): error MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
2020-03-15T09:39:00.5438012Z     Done Building Project "D:\bld\stir_1584264789343\work\build\CMakeFiles\3.16.4\VCTargetsPath.vcxproj" (default targets) -- FAILED.
2020-03-15T09:39:00.5438555Z     
2020-03-15T09:39:00.5438790Z     Build FAILED.
```
I guess we're missing something somewhere but I have no clue.

OSX build [fails with a seg-fault](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=131276&view=logs&j=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&t=113b264d-9551-5065-da10-7eb3bdeaf1bc&l=25099). This seems hopeless to debug remotely.

**Comment by KrisThielemans** [comment]
I've removed the OSX build. It'll need debugging in a different PR

**Comment by KrisThielemans** [comment]
On the recommendation of https://github.com/conda-forge/conda-forge.github.io/issues/703, I've switched to using Ninja (also used by [libitk-feedstock](https://github.com/conda-forge/libitk-feedstock/blob/master/recipe/bld.bat)

**Comment by KrisThielemans** [comment]
success!

**Pull request merged**
