### PR TITLE
upgrade to STIR 4.0.0-alpha

### PR DESCRIPTION
**Pull request by KrisThielemans**
also use git as opposed to zip to avoid  having to compute sha256

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by KrisThielemans** [comment]
@conda-forge-admin please rerender

**Comment by KrisThielemans** [comment]
@paskino @casperdcl could you help with the re-rendering?

**Comment by KrisThielemans** [comment]
failures in docker builds due to
```
Error: bad character '-' in package/version: 4.0.0-alpha
```

**Comment by KrisThielemans** [comment]
failed with
```
Cloning into bare repository '/home/conda/feedstock_root/build_artifacts/git_cache/github.com/UCL/STIR.git'...
Cloning into '/home/conda/feedstock_root/build_artifacts/stir_1576244527824/work'...
checkout: 'stir_rel_4_00_alpha'
error: pathspec 'stir_rel_4_00_alpha' did not match any file(s) known to git
Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
Error was: 
Command '['/opt/conda/bin/git', 'checkout', 'stir_rel_4_00_alpha']' returned non-zero exit status 1.
Failed to download or patch source. Please see build log for info.
```
Probably related to the fact that `git clone --depth=1` doesn't get any tags (it just gets the last commit on `master`)

**Comment by KrisThielemans** [comment]
I've done the re-render. might be good to go

**Comment by KrisThielemans** [comment]
@paskino, @casperdcl, @olivierverdier this is done. I only hesitate because of version numbering. Does it matter that version is 4.0.0.alpha?

**Comment by KrisThielemans** [comment]
seems anaconda recomments [PEP40](https://www.python.org/dev/peps/pep-0440/). I've changed the version accordingly.

**Comment by msarahan** [comment]
Tarballs are preferred:
https://conda-forge.org/docs/maintainer/adding_pkgs.html#build-from-tarballs-not-repos

**Pull request merged**
