### PR TITLE
Dev reset to #96

### PR DESCRIPTION
**Pull request by KrisThielemans**
#96 was incorrectly merged to `main` as opposed to `dev`. Trying to correct that by merging current `main` back onto `dev`.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by KrisThielemans** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
> Trying to correct that by merging current `main` back onto `dev`.

You're not correcting anything on `main` by changing the content of `dev`.

**Comment by KrisThielemans** [comment]
sure, but I had to fix the `dev` branch first (as `main` had the content of #96).

Correcting `main` will be a different PR.

**Comment by h-vetinari** [comment]
> sure, but I had to fix the `dev` branch first (as `main` had the content of #96).

This is not how git works -- the content of the branch `dev` has nothing to do with `main`, and further layering changes on top of `dev` will not make it easier if you later try to merge anything back from `dev` to `main`.

I already described in #97  how you can roll main back to the state before the merge of #96 - checkout the content of the commit before the merge and commit that. To find the commit before the merge:

image

```
git checkout main       # ensure this is up-to-date with the remote main branch
git checkout -b rewind  # new branch
git checkout d488953f31fb0f38eee514d5f1d24dc1c7c1f2c9 -- .  # check out all files (the dot in `-- .`) at the specified commit
git commit -m "reset recipe back to state before mistakenly merging #96"
git push origin rewind
```

**Comment by KrisThielemans** [comment]
thanks @h-vetinari but I think I'll disagree here, but this is probably related my choice on maintaining `dev` and `main`.

> the content of the branch `dev` has nothing to do with `main`, and further layering changes on top of `dev` will not make it easier if you later try to merge anything back from `dev` to `main`.

I'm aware that the contents of the branches are independent (until you merge of course). Let me try to clarify the history and hence explain my rationale:
1. I branched off `dev` from `main`, and modified the recipe to point to more recent STIR
2. various (automatic or not) PRs were merged onto `main`
3. I created #96, where I created a branch from `dev`, merged `main` to that branch (but mistakenly told github to merge that PR to `main`).
4. I merged #96 (to `main` therefore)
5. I created this PR #99 to merge (the now updated) `main` to `dev`

My intention was to have `dev` (almost) identical to what it would have been if I had correctly set `dev` as target for #96. As far as I understand, this is the case (I'm not sure why i had some merge conflicts in the generated files, but let's ignore that). `dev` indeed has the merge with (old) `main` (as well as the new one), and therefore contains the PRs from step 2 above. 

The above steps 1-3 seem to me a good way to keep `dev` up to date with `main`, and hence the automatic updates from conda-forge (as long as I don't make that stupid mistake ever again of course!). In fact, if I merge `dev` to `main`. `main` will presumably get the `meta.yml` changes with the dev build number etc, which would be incorrect. I do realise that if  recent STIR (i.e. `dev`) needs extra dependencies, it does seem appropriate to then merge `dev` to `main` whenever we've got a STIR release. I suppose that I'd then need to handle the dev build problem.

Maybe I've got this all wrong... Hence my question in #97 on how to manage `main` and `dev`. This makes my head hurt...

In any case, I think I'll wait a bit longer before touching `main`!

Thanks again for your help.

**Comment by h-vetinari** [comment]
> In any case, I think I'll wait a bit longer before touching `main`!

No, you definitely need to fix main. I don't care if you roll-back to something that was working previously, or advance to whatever the future is, but don't leave the feedstock in a state where it cannot be built.

**Pull request merged**
