### PR TITLE
add build for osx_arm64

### PR DESCRIPTION
**Pull request by gschramm**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gschramm** [comment]
@conda-forge-admin, please rerender

**Comment by KrisThielemans** [comment]
```
  Could NOT find Python (missing: Python_NumPy_INCLUDE_DIRS Interpreter
  NumPy) (found version "2.7.16")
```
???

**Comment by KrisThielemans** [comment]
now we're getting into my confusion between `build` and `host` again (which you tried to explain to me). oh well.

I can't see how moving `python` only can work, but then, cross-compilation is a bit of a mystery to me.

good luck :-)

**Comment by gschramm** [comment]
@conda-forge-admin, please rerender

**Comment by gschramm** [comment]
seems harder than I thought - who could have know that in advance ;)

osx_arm64 fails with:
```
$SRC_DIR/src/include/stir/listmode/CListRecordGEHDF5.h:80:7: error: C++ requires a type specifier for all declarations
      TODO;
```

osx builds and tests but does not install

windows is missing python.

conclusion: I don't understand `build` vs `host` requirements

**Comment by KrisThielemans** [comment]
> $SRC_DIR/src/include/stir/listmode/CListRecordGEHDF5.h:80:7: error: C++ requires a type specifier for all declarations
>       TODO;

https://github.com/UCL/STIR/blob/master/src/include/stir/listmode/CListRecordGEHDF5.h#L78-L81 say this
```c++
    {
    public:
#if STIRIsNativeByteOrderBigEndian
      // Do byteswapping first before using this bit field.
      TODO;
#else
```
I didn't know Mac's arm are big-endian. This isn't a trivial change and can only be sorted by coding+testing. You could remove HDF5 support for this build (like we do for Windows, as that has a link problem in conda for some reason).

**Comment by KrisThielemans** [comment]
I found https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/, which talks about a bot that can do it, or what we have to do ourselves. No idea if that information is still up-to-date.

**Comment by dopplershift** [comment]
I'd recommend structuring the dependence on numpy and python in `host` vs. `build` for cross-compiling like we do here e.g. in matplotlib: https://github.com/conda-forge/matplotlib-feedstock/blob/9bbfdc73f8bb4bf7f328f9c01671947f5c5fda3d/recipe/meta.yaml#L25-L46

**Comment by gschramm** [comment]
> I'd recommend structuring the dependence on numpy and python in `host` vs. `build` for cross-compiling like we do here e.g. in matplotlib: https://github.com/conda-forge/matplotlib-feedstock/blob/9bbfdc73f8bb4bf7f328f9c01671947f5c5fda3d/recipe/meta.yaml#L25-L46

@dopplershift after changing the requirements, all non-cross compilation builds seem to work (the one failed is due to a known issue). unfortunately, the `osx_arm64` fail with an error that I don't understand - see [here](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/664142/logs/189)

**Comment by KrisThielemans** [comment]
@conda-forge-admin, please rerender

**Comment by KrisThielemans** [comment]
Many thanks @dopplershift for your suggestion! Please ignore the error flagged up by @gschramm . Seems he didn't read https://github.com/conda-forge/stir-feedstock/pull/72#issuecomment-1444436097 yet. I've now excluded hdf5 which might resolve that.

Checking https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock, we still might have to add `CMAKE_ARGS` and not run the `ctests` in our `build.sh`

**Comment by KrisThielemans** [comment]
> Checking https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock, we still might have to add `CMAKE_ARGS` and not run the `ctests` in our `build.sh`

I've done that now. (and also forced disabling of HDF5 functionality in STIR on osx_arm64, as it had found it anyway)

**Comment by KrisThielemans** [comment]
I'm struggling to disable HDF5 due to https://github.com/UCL/STIR/issues/1165

**Comment by KrisThielemans** [comment]
Success! Although of course it isn't running any tests at all.

Currently I disabled HDF5 and ITK in the build.sh, while ITK is still in the recipe. That's a bit wasteful, but I'm too lazy to fix it, as we won't need that anymore (I hope!) in 5.2.

**Comment by KrisThielemans** [comment]
I'll merge this now. thanks all for your help!

**Pull request merged**
