### PR TITLE
update dev to STIR master 14May2024

### PR DESCRIPTION
**Pull request by KrisThielemans**
Set to current STIR

Also take some features from https://github.com/conda-forge/stir-feedstock/pull/111, i.e. https://conda-forge.org/news/2024/03/24/stdlib-migration/

### CODE REVIEW

**Comment by KrisThielemans** [comment]
@conda-forge-admin rerender

**Comment by KrisThielemans** [comment]
@conda-forge-admin please rerender

**Comment by KrisThielemans** [comment]
@conda-forge/core I don't know how to proceed here. rerender give an error:

https://github.com/conda-forge/stir-feedstock/actions/runs/9086596117/job/24972628026#step:3:576
```
  File "/opt/conda/lib/python3.11/site-packages/conda_smithy/variant_algebra.py", line 66, in _version_order
    return ordering.index(v)
           ^^^^^^^^^^^^^^^^^
ValueError: '11.8' is not in list
```
could be CUDA.

Dependencies are likely out-of-date. The `main` branch is stuck due to a ROOT problem, which I have now (possibly) fixed on STIR `master`, so I wanted to test this first to make a new `dev` release.

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
> @conda-forge/core I don't know how to proceed here.

It's a bit of a hard-to-diagnose problem. 🙃 
Should be fixed now though.

**Comment by KrisThielemans** [comment]
amazing @h-vetinari thanks a lot.

**Pull request merged**
