### PR TITLE
add parallelproj run cpu/cuda requirement

### PR DESCRIPTION
**Pull request by gschramm**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gschramm** [comment]
@conda-forge-admin, please rerender

**Comment by gschramm** [comment]
after studying the MPI build examples in the conda-forge [knowledge base](https://conda-forge.org/docs/maintainer/knowledge_base.html#complete-example), I hope adding the parallelproj run req. will solve the install problems

**Comment by gschramm** [comment]
Seems that at the very end of the [linux non-cuda build](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/665314/logs/209), now the parallelproj cpu version gets installed :)
```
2023-02-28T03:07:55.5336425Z     parallelproj:                         1.2.14-cpuhd8589cd_0       conda-forge
```

**Comment by gschramm** [comment]
So I think, that now at least
```
mamba install stir=*=*cpu*
```
and
```
mamba install stir=*=*cpu*
```
should install the correct parallelproj versions

**Comment by gschramm** [comment]
I will also look more into `run_exports` tomorrow for `parallelproj` such that we might not need the `run` requirements in the future

**Comment by KrisThielemans** [comment]
> So I think, that now at least ...

I guess you meant `conda` in one of them, as now both lines are the same.

**Comment by KrisThielemans** [comment]
I'm not sure if this PR achieves anything to resolve our problems.

At installation time, the stir-cpu version would be entirely happy with the parallelproj-cuda install, as it effectively includes parallelproj-cpu anyway.  Of course, stir-cuda needs parallelproj-cuda, and it's possible that we might have to enforce that, like you do in this PR, but it solves a problem that we haven't seen yet.

By the way, I'd argue that for parallelproj, people would be happy with only have the cuda versions of the package. They can run the cpu version if they want (and there are no differing files, only extra ones I believe). So, but the problems in #70 (i.e. that conda installs stir-cuda version on a system without cuda are really for STIR).

Of course, I'm happy to merge this PR anyway if you like.

**Comment by gschramm** [comment]
Hi Kris,

1. It is better not to merge the PR yet. A few conda-forge people are looking into the problem right now.
2. I don't know how the package resolution is implemtend in conda vs mamba (obviously there seems to be a difference).
So it might be best to recommend to always use ```conda/mamba install stir=*=cpu*``` or ```conda/mamba install stir=*=cuda*``` depending on what you want.
3. With my current efforts, I want to make sure that at least if someone uses ```conda/mamba install stir=*=cpu*```, the cpu version of `parallelproj` gets installed (on all platforms). Is that the case right now? I thought that mamba sometimes still installs the cuda version. I could, however, be that this should be fixed with `run_exports` in the `parallelproj` recipe instead of modifying the `stir` recipe. Let's see what the conda-forge experts say.

**Comment by gschramm** [comment]
could it be that the problem is due to the fact, that `parallelproj_cuda` does not depend on the `cudatoolkit`? Currently, all dependencies of `parallelproj_cuda` can be also installed/used on non-cuda systems, which I guess confuses the mamba package resolution

**Comment by KrisThielemans** [comment]
> I'd argue that for parallelproj, people would be happy with only have the cuda versions of the package. They can run the cpu version if they want (and there are no differing files, only extra ones I believe).

Ok, this isn't quite true. I think the only files that are different between the 2 versions are the exported CMake files. For instance, `parallelprojConfig.cmake` contains the following in the CUDA version of course
```
  set(parallelproj_built_with_CUDA TRUE)
```

so yes, you do need CUDA and non-CUDA versions of parallelproj

**Comment by gschramm** [comment]
> > I'd argue that for parallelproj, people would be happy with only have the cuda versions of the package. They can run the cpu version if they want (and there are no differing files, only extra ones I believe).
> 
> Ok, this isn't quite true. I think the only files that are different between the 2 versions are the exported CMake files. For instance, `parallelprojConfig.cmake` contains the following in the CUDA version of course
> 
> ```
>   set(parallelproj_built_with_CUDA TRUE)
> ```
> 
> so yes, you do need CUDA and non-CUDA versions of parallelproj

1. the cuda version of parallelproj ships the non-cuda and cuda version of the libs (`libparallelproj_c.so` and `libparallelproj_cuda.so`). But as you say `set(parallelproj_built_with_CUDA TRUE)` is the difference.
2. Is there a fundamental way for STIR to determine at runtime which version of `libparallelproj` to use that also takes into account whether a cuda GPU is present at runtime? I guess a test like: `parallelproj_built_with_CUDA == TRUE` and `physical cuda GPU == present`?

**Pull request closed without merging**
